Algoritmo "Exercicio05"
//  
// Professor   : Aldo Henrique
// Descrição   : Lista de Exércicio de Algoritmos
// Autor(a)    : Mylena Costa de Souza
// Data atual  : 22/02/2019
Var
// Seção de Declarações das variáveis 
  a : inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
   escreval("Digite um número inteiro:")
   leia(a)
   
   escreval("O quadrado deste número inteiro é:",(a*a))

Fimalgoritmo