Algoritmo "Exercicio03"
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 17/03/2019
Var
   // Seção de Declarações das variáveis

   x:real
   i:inteiro
   soma:real
   num:real

Inicio
   // Seção de Comandos, procedimento, funções, operadores, etc...
   soma<- 0
   x<-1
   para i de 1 ate 50 faca

      soma <- (x/i)+soma
      x <- x+2
   fimpara

   escreval ("Soma = ", soma)

Fimalgoritmo
