Algoritmo "Exercicio02"
// Descrição   : Tabuada de 0 a 9
// Autor(a)    : Mylena Costa de Souza
// Data atual  : 16/03/2019
Var
   // Seção de Declarações das variáveis
   i,num:inteiro
Inicio
   // Seção de Comandos, procedimento, funções, operadores, etc...
   escreval("escreva um numero de 1 a 9: ")
   leia(num)
   para i de 0 ate 9 faca
      escreval (num," x",i," =",i*num)
   fimpara
fimalgoritmo