Algoritmo "Exercicio04"
// Descrição   :  Algoritmo que gera números entre 1000 e 1999 e
//mostra aqueles que divididos por 11 dão resto 5.
// Autor(a)    : Mylena Costa de Souza
// Data atual  : 16/03/2019
Var
   // Seção de Declarações das variáveis
   num:inteiro

Inicio
   // Seção de Comandos, procedimento, funções, operadores, etc...
   para num de 1000 ate 1999 faca
      se (num % 11 = 5) entao
         escreva (num)
      fimse
   fimpara
Fimalgoritmo